### PR TITLE
Use StreamReader to detect encoding.

### PR DESCRIPTION
**Pull request by jlaanstra**
File.WriteAllText by default uses Encoding.Default which changes the encoding for xaml files that are proicessed as VS by default uses UTF8. This change uses the detection capabilities of StreamReader and use the detected encoding to write the output.

### CODE REVIEW

**Comment by grochocki** [comment]
Thanks Johan!

**Comment by jlaanstra** [comment]
Any chance we can get a new build out with this change?

**Comment by grochocki** [comment]
Would rather not push an update to the extension, since the changes were localized to xmagic.exe, which is not included in the VSIX. I bundled the changes from this PR into a standalone download [here](https://github.com/grochocki/XamlMagic/files/133601/xmagic.zip).

**Comment by jlaanstra** [comment]
Thanks @grochocki!

**Pull request merged**
